Repository mattermost/mattermost-plugin-github, pull requests merged in 2019-06, with the labels that each got.

#81 Update github.com/google/go-github
  go.mod
  go.sum
  server/api.go
  server/command.go
  server/plugin.go
  server/subscriptions.go
  server/webhook.go
Labels: 3: Reviews Complete

#80 Proposed help text update for EnablePrivateRepo setting
  plugin.json
Labels: 2: Dev Review

#79 Moving to using unified github deploy.
  .circleci/config.yml
Labels: 2: Dev Review

#83 Using a bot account.
  README.md
  plugin.json
  server/api.go
  server/command.go
  server/configuration.go
  server/plugin.go
  server/webhook.go
Labels: 2: Dev Review

#85 New FAQ: How does the plugin save user data for each connected GitHub user?
  README.md
Labels: 2: Dev Review

#88 Fix error handling
  server/plugin.go
Labels: 3: Reviews Complete

#87 MM-16038 Improving oauth connect flow.
  server/api.go
Labels: 2: Dev Review

#89 Clarify how to access features as end user
  README.md
Labels: 2: Dev Review

#92 Updating dependencies to pull in MM-16114
  go.mod
  go.sum
Labels: 2: Dev Review

#91 GH-90 Added checking for updates before sending daily update
  server/api.go
  server/plugin.go
Labels: 2: Dev Review

#96 README update: format setting config for better usability
  README.md
Labels: 3: Reviews Complete

#97 add Installation section
  README.md
Labels: 2: Dev Review

#73 leverage templates for webhook messages
  go.mod
  go.sum
  server/plugin.go
  server/template.go
  server/template_test.go
  server/webhook.go
Labels: 3: Reviews Complete, Do Not Merge

#98 extend fixGithubNotificationSubjectURL to commits
  server/utils.go
  server/utils_test.go
Labels: 3: Reviews Complete

#99 Update GitHub plugin introduction with authorization callback URL
  plugin.json
Labels: 3: Reviews Complete

#102 Update Header text and instructions
  plugin.json
Labels: 2: Dev Review
