Repository mattermost/mattermost-plugin-github, pull requests merged in 2019-03, with the labels that each got.

#52 GitHub Subscribe Organization
  server/command.go
  server/subscriptions.go
  server/utils.go
  server/utils_test.go
Labels: 1: PM Review, 2: Dev Review

#50 Serve the profile image for the plugin from the plugin itself
  Makefile
  assets/profile.png
  server/api.go
  server/command.go
  server/configuration.go
  server/plugin.go
  server/webhook.go
Labels: 3: Ready to Merge

#60 deploy to GH when tag a release
  .circleci/config.yml
Labels: 3: Ready to Merge

#59 Fixed issue with SubscribeOrg adding objects as keys
  server/subscriptions.go
Labels: 2: Dev Review

#62 fix name to push to GH
  .circleci/config.yml
Labels: 3: Ready to Merge

#61 Add a screenshot to README.md
  README.md
Labels: 2: Dev Review

#64 Fix paging for Subscribe Organization
  server/subscriptions.go
Labels: 2: Dev Review

#63 Fix #48: Use IssueCommentEvent's action in post msg
  server/webhook.go
Labels: 2: Dev Review

#65 Skip notification for edit/delete of comments on issues
  server/webhook.go
Labels: 2: Dev Review
