Repository mattermost/mattermost-plugin-github, pull requests merged in 2020-10, with the labels that each got.

#376 Use issue icon in RHS
  webapp/src/components/sidebar_right/github_items.jsx
Labels: 4: Reviews Complete

#374 Release v2.0.0-rc2
  plugin.json
  server/plugin/manifest.go
  webapp/src/manifest.ts
Labels: 4: Reviews Complete

#305 Release v2.0.0
  README.md
  plugin.json
  server/plugin/manifest.go
  webapp/src/manifest.ts
Labels: 4: Reviews Complete

#383 Use pluginID instead of Hardcoded "github" string
  server/plugin/command.go
  webapp/src/client/client.js
  webapp/src/index.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#394 Fixes 324
  server/plugin/api.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#393 Fix issue labeling double message
  server/plugin/webhook.go
Labels: 4: Reviews Complete, AutoMerge, Hacktoberfest, hacktoberfest-accepted
