Repository mattermost/mattermost-plugin-github, pull requests merged in 2020-11, with the labels that each got.

#400 Subscription using --exclude-org-member flag should fail without locked org
  server/plugin/plugin.go
  server/plugin/subscriptions.go
Labels: 4: Reviews Complete, Hacktoberfest, Lifecycle/1:stale, hacktoberfest-accepted

#402 [FIX] Handle Issue Creation failures in the correct place
  server/plugin/api.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#392 Separate Post for Creating Issues
  server/plugin/command.go
  server/plugin/subscriptions.go
  server/plugin/template.go
  server/plugin/webhook.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#293 Use official github icons
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/sidebar_right/github_items.jsx
  webapp/src/images/icons/changes_requested.jsx
  webapp/src/images/icons/cross.jsx
  webapp/src/images/icons/dot.jsx
  webapp/src/images/icons/sign.jsx
  webapp/src/images/icons/tick.jsx
Labels: 4: Reviews Complete
