Repository mattermost/mattermost-plugin-github, pull requests merged in 2020-03, with the labels that each got.

#198 [MM-22697] Replace Github with GitHub everywhere
  server/command.go
  server/template_test.go
  webapp/package.json
  webapp/src/components/github_issue_selector.jsx
  webapp/src/index.js
Labels: 3: Reviews Complete, QA Review Done

#201 Subscribe list is sorted by the repo name
  server/subscriptions.go
  server/subscriptions_test.go
Labels: 3: Reviews Complete, QA Review Done

#192 Make links in todo messages consistent
  server/command.go
  server/plugin.go
  server/subscriptions.go
  server/utils.go
  server/utils_test.go
  server/webhook.go
Labels: QA Review Done

#200 Require read:org scope for OAuth connect
  server/plugin.go
Labels: 3: Reviews Complete, QA Review Done

#123 Adding create issue modal
  server/api.go
  webapp/src/action_types/index.js
  webapp/src/actions/index.js
  webapp/src/client/client.js
  webapp/src/components/github_repo_selector.jsx
  webapp/src/components/input.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/modals/create_issue/index.js
  webapp/src/components/post_menu_action/create_issue/create_issue.jsx
  webapp/src/components/post_menu_action/create_issue/index.js
  webapp/src/index.js
  webapp/src/reducers/index.js
Labels: 2: QA Review, Docs/Needed

#221 fix linting error
  webapp/src/components/post_menu_action/create_issue/create_issue.jsx
Labels: 3: Reviews Complete

#210 [MM-22640] Make access to private repos opt-in
  server/api.go
  server/command.go
  server/plugin.go
Labels: 3: Reviews Complete, QA Review Done

#196 Bump version to 0.14.0
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 3: Reviews Complete, QA Review Done

#230 go mod tidy
  go.sum
Labels: 3: Reviews Complete

#168 Added golangci.yml file to repo
  .golangci.yml
  Makefile
  server/api.go
  server/command.go
  server/template_test.go
  server/webhook.go
Labels: 3: Reviews Complete

#229 [GH-220] Add attach and create post action features to the README
  README.md
Labels: 3: Reviews Complete
