Repository mattermost/mattermost-plugin-github, pull requests merged in 2020-01, with the labels that each got.

#169 Bump Mattermost to 5.18
  build/manifest/main.go
  go.mod
  go.sum
  server/api.go
  server/command.go
  server/configuration.go
  server/main.go
  server/permalinks_test.go
  server/plugin.go
  server/subscriptions.go
  server/template.go
  server/template_test.go
  server/webhook.go
Labels: 3: Reviews Complete

#154 Exclude organization members feature
  README.md
  server/command.go
  server/plugin.go
  server/subscriptions.go
  server/utils.go
  server/utils_test.go
  server/webhook.go
Labels: 3: Reviews Complete, Docs/Needed

#162 GH-124 Improve "Attach to Issue" function
  server/api.go
  server/utils.go
  webapp/src/components/github_issue_selector.jsx
  webapp/src/components/icon.jsx
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/attach_comment_to_issue/index.js
  webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/utils/styles.js
Labels: 2: Dev Review, Lifecycle/1:stale

#172 Fixes #171 : Remove comments before posting a notification
  server/template.go
  server/template_test.go
Labels: 3: Reviews Complete

#177 GH-176 Replace GitHub usernames in body of notifications
  server/template.go
  server/template_test.go
Labels: 3: Reviews Complete

#181 Bump version to 0.13.0
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 3: Reviews Complete, QA Review Done
