Repository mattermost/mattermost-plugin-github, pull requests merged in 2023-02, with the labels that each got.

#630 Bump scss-tokenizer, sass-loader and node-sass in /webapp
  webapp/package-lock.json
  webapp/package.json
Labels: 4: Reviews Complete, Contributor

#598 Add build info
  go.mod
  go.sum
  plugin.json
  server/plugin/command.go
  server/plugin/plugin.go
Labels: 4: Reviews Complete

#644 Update GitHub actions workflow
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  webapp/package-lock.json
  webapp/package.json
Labels: 4: Reviews Complete

#632 [GH-500]: Fixed github issue "Emoji synchronisation for PR/issue on github"
  server/plugin/plugin.go
  server/plugin/webhook.go
Labels: 4: Reviews Complete, Contributor

#596 Move font color to outer span so it is applied to the overflow text
  webapp/src/components/link_tooltip/link_tooltip.jsx
Labels: 4: Reviews Complete, Contributor

#600 Extend githubPermalinkRegex
  server/plugin/plugin.go
Labels: 4: Reviews Complete, Docs/Not Needed, Contributor

#462 mm-241 - adds aria labels to right hand side elements
  webapp/src/components/sidebar_right/github_items.tsx
Labels: 4: Reviews Complete

#633 [GH-558]:Fixed github issue "Duplicate notifications in case of mention and assignee"
  server/plugin/template.go
  server/plugin/webhook.go
Labels: 4: Reviews Complete
