Repository mattermost/mattermost-plugin-github, pull requests merged in 2023-11, with the labels that each got.

#697 [GH-692] Fix formatting inside code block in issue created notification
  server/plugin/webhook.go
Labels: 3: QA Review

#708 Bump version to 2.1.7
  plugin.json
  server/plugin/webhook.go
Labels: 3: QA Review

#699 [GH-693] Fix improper rendering of some unreads in the response of "/github todo" command
  server/plugin/plugin.go
  server/plugin/utils.go
  server/plugin/utils_test.go
Labels: 4: Reviews Complete

#664 [GH-378]:Fixed issue #378 'Check for webhook while subscribing'
  server/plugin/command.go
Labels: 4: Reviews Complete, Contributor

#683 [GH-418]: Fixed issue #418 'Added --exclude option to subscriptions command'.
  README.md
  server/plugin/command.go
  server/plugin/subscriptions.go
Labels: 4: Reviews Complete, Contributor

#661 [GH-512,513] Fixed issue #512 and #513 on github plugin 'Updated subscription success messages'
  server/plugin/command.go
  server/plugin/subscriptions.go
Labels: 4: Reviews Complete, Contributor
