Repository mattermost/mattermost-plugin-github, pull requests merged in 2023-05, with the labels that each got.

#666 Playwright suite on CI + me/todo/autocomplete specs
  .github/workflows/playwright.yml
  build/custom.mk
  build/setup.mk
  e2e/playwright/.eslintrc.json
  e2e/playwright/.gitignore
  e2e/playwright/README.md
  e2e/playwright/mock_oauth_server/.env.sample
  e2e/playwright/mock_oauth_server/index.ts
  e2e/playwright/mock_oauth_server/mock_oauth_server.ts
  e2e/playwright/package-lock.json
  e2e/playwright/package.json
  e2e/playwright/playwright.config.ts
  e2e/playwright/setup-environment
  e2e/playwright/support/components/post.ts
  e2e/playwright/support/components/slash_commands.ts
  e2e/playwright/support/components/todo_message.ts
  e2e/playwright/support/constants.ts
  e2e/playwright/support/init_mock_oauth_server.ts
  e2e/playwright/support/init_test.ts
  e2e/playwright/support/kv.ts
  e2e/playwright/support/user.ts
  e2e/playwright/support/utils.ts
  e2e/playwright/tests/command/autocomplete.spec.ts
  e2e/playwright/tests/command/me.spec.ts
  e2e/playwright/tests/command/todo.spec.ts
  e2e/playwright/tests/github_plugin.spec.ts
  e2e/playwright/tests/integrations.setup.ts
  e2e/playwright/tests/test.list.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/sidebar_buttons/sidebar_buttons.jsx
  webapp/webpack.config.js
Labels: 2: Dev Review

#671 [MM-52397] Move client package into root directory
  client/client.go
  client/client_test.go
Labels: 4: Reviews Complete

#678 Added explanation for /setup command
  README.md
Labels: 2: Dev Review, Contributor

#679 [MM-42918] Add debug information for setup wizard
  server/plugin/flows.go
  server/plugin/plugin.go
  server/plugin/utils.go
  server/plugin/utils_test.go
Labels: 2: Dev Review, 3: QA Review
