Repository mattermost/mattermost-plugin-github, pull requests merged in 2024-11, with the labels that each got.

#838 [MM-874]: Fixed the issue of LHS not working without setting organisation lock
  server/plugin/graphql/lhs_request.go
Labels: 4: Reviews Complete

#765 [MM-356] Add feature to subscribe to release and workflow events
  server/plugin/command.go
  server/plugin/subscriptions.go
  server/plugin/template.go
  server/plugin/template_test.go
  server/plugin/webhook.go
Labels: Lifecycle/1:stale, 3: QA Review

#833 [MM-401]: Added pr/issue opened by in tooltip modal
  webapp/src/components/link_tooltip/link_tooltip.jsx
  webapp/src/components/link_tooltip/tooltip.css
Labels: 3: QA Review

#840 [MM-141]: Made access to KV store atomically safe when saving/removing subscriptions
  server/plugin/plugin.go
  server/plugin/subscriptions.go
Labels: 2: Dev Review, 3: QA Review

#825 [MM-468]: Include number of lines changed in RHS PR list
  server/plugin/api.go
  server/plugin/graphql/lhs_query.go
  server/plugin/graphql/lhs_request.go
  webapp/src/components/sidebar_right/github_items.tsx
  webapp/src/types/github_types.ts
Labels: 4: Reviews Complete

#829 Fix missing PR notifications when using both pulls_created and pulls_merged features filter
  server/plugin/webhook.go
Labels: Lifecycle/1:stale, 3: QA Review, Contributor

#763 Fixes #497: "Validation Message spacing (UI) issue"
  webapp/src/components/github_repo_selector/github_repo_selector.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/react_select_setting.jsx
  webapp/src/components/setting.jsx
Labels: 4: Reviews Complete, Contributor

#854 [MM-946]: Added testcases for some functions in command.go
  server/plugin/command_test.go
Labels: 2: Dev Review
