Repository mattermost/mattermost-plugin-github, pull requests merged in 2024-07, with the labels that each got.

#770 Update subscription messages with respect to webhook
  server/plugin/command.go
Labels: 3: QA Review

#768 [MM-405]: Fixed the pull review request events not working
  server/plugin/template.go
  server/plugin/template_test.go
  server/plugin/webhook.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/sidebar_right/github_items.tsx
  webapp/src/constants/index.js
Labels: 2: Dev Review, 3: QA Review

#798 Update CODEOWNERS
  CODEOWNERS
  README.md
Labels: 2: Dev Review

#761 [MM-350] Fix issue in create issue modal and attach issue modal
  server/plugin/api.go
  webapp/src/actions/index.ts
Labels: 2: Dev Review

#767 [GH-670] Fix issue: Code previews not working for branches
  server/plugin/permalinks.go
  server/plugin/permalinks_test.go
  server/plugin/plugin.go
Labels: 3: QA Review

#773 [MM-420] Add feature to support multiple orgs in plugin settings
  plugin.json
  server/plugin/api.go
  server/plugin/configuration.go
  server/plugin/configuration_test.go
  server/plugin/graphql/client.go
  server/plugin/graphql/lhs_request.go
  server/plugin/plugin.go
  server/plugin/utils.go
  server/plugin/webhook.go
  webapp/src/components/sidebar_right/index.jsx
  webapp/src/components/sidebar_right/sidebar_right.jsx
  webapp/src/reducers/index.ts
  webapp/src/selectors.ts
  webapp/src/types/github_types.ts
Labels: 3: QA Review
