Repository mattermost/mattermost-plugin-github, pull requests merged in 2024-02, with the labels that each got.

#729 [GH-719] Pushed commits events: add option to show Author instead of committer
  plugin.json
  server/plugin/configuration.go
  server/plugin/template.go
  server/plugin/template_test.go
  server/plugin/webhook.go
Labels: 4: Reviews Complete, Contributor

#738 Update CODEOWNERS to include mickmister
  CODEOWNERS
  README.md
Labels: 4: Reviews Complete

#709 Bump version to 2.2.0.
  plugin.json
Labels: 3: QA Review

#725 [MM-53944] Make use of github.com/mattermost/mattermost/server/public
  build/custom.mk
  build/go.mod
  build/go.sum
  build/manifest/main.go
  build/pluginctl/main.go
  build/sync/plan.yml
  client/client_test.go
  go.mod
  go.sum
  plugin.go
  server/main.go
  server/plugin/api.go
  server/plugin/api_test.go
  server/plugin/cluster.go
  server/plugin/command.go
  server/plugin/configuration.go
  server/plugin/flows.go
  server/plugin/graphql/client.go
  server/plugin/mm_34646_token_refresh.go
  server/plugin/permalinks_test.go
  server/plugin/plugin.go
  server/plugin/subscriptions_test.go
  server/plugin/telemetry.go
  server/plugin/utils_test.go
  server/plugin/webhook.go
Labels: 4: Reviews Complete

#727 [MM-36] Update plugin with respect to phase 1 upgrades
  .gitignore
  .nvmrc
  Makefile
  README.md
  build/legacy.mk
  build/manifest/main.go
  build/pluginctl/logs.go
  build/pluginctl/logs_test.go
  build/pluginctl/main.go
  build/setup.mk
  plugin.json
  server/plugin/command.go
  server/plugin/plugin.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/action_types/index.js
  webapp/src/actions/index.js
  webapp/src/client/client.js
  webapp/src/components/github_repo_selector/index.js
  webapp/src/components/link_tooltip/index.jsx
  webapp/src/components/modals/attach_comment_to_issue/index.js
  webapp/src/components/modals/create_issue/index.js
  webapp/src/components/post_menu_action/create_issue/index.js
  webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/post_menu_actions/attach_comment_to_issue/index.js
  webapp/src/components/sidebar_buttons/index.js
  webapp/src/components/user_attribute/index.js
  webapp/src/index.js
  webapp/src/manifest.test.ts
  webapp/src/manifest.ts
  webapp/src/selectors.js
  webapp/src/websocket/index.js
  webapp/webpack.config.js
Labels: 4: Reviews Complete, Do Not Merge
