Repository mattermost/mattermost-plugin-github, pull requests merged in 2024-03, with the labels that each got.

#745 Adopt memorystore for tests
  go.mod
  go.sum
  server/plugin/api.go
  server/plugin/command.go
  server/plugin/configuration.go
  server/plugin/graphql/client.go
  server/plugin/mm_34646_token_refresh.go
  server/plugin/plugin.go
  server/plugin/subscriptions.go
  server/plugin/subscriptions_test.go
  server/plugin/telemetry.go
  server/plugin/webhook.go
Labels: 4: Reviews Complete

#736 [GH-733] Updated the "issue_creations" subscription to post notification when an issue is labeled/reopened
  server/plugin/command.go
  server/plugin/webhook.go
Labels: 3: QA Review

#751 Bump go version for playwright test
  .github/workflows/playwright.yml
Labels: 2: Dev Review

#753 Fix flaky TestFilterLogEntries
  build/pluginctl/logs_test.go
Labels: 4: Reviews Complete
